### ISSUE TITLE
NameError in logs

### ISSUE THREAD

**Issue by curable-online** [TheWeirdDev/nautilus-send-to-bluetooth#2]
Not sure if it's important or not.
However, running nautilus from the terminal, even though successful, leaves the following error to the terminal:

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/SendToBluetooth.py", line 1, in <module>

……

title":"nautilus-send-to-bluetooth/SendToBluetooth.py at master · TheWeirdDev/nautilus-send-to-bluetooth"}
                                      ^^^^^
NameError: name 'false' is not defined. Did you mean: 'False'?
```

The whole log is pretty long, I just paste what I thought to be useful.

**Comment by TheWeirdDev** [comment]
What version of nautilus are you using?

I cannot reproduce the error on my system, and the word 'false' doesn't exist anywhere in the source code. Can you provide the full logs?

**Comment by curable-online** [comment]
GNOME nautilus 45.2.1

So it's probably something with my own system's Bluetooth configurations.

**Comment by curable-online** [comment]
That is the full log: [log.txt](https://github.com/TheWeirdDev/nautilus-send-to-bluetooth/files/14499313/log.txt)

**Comment by TheWeirdDev** [comment]
Did you install the extension by copying and pasting the content into a new file? seems like it wasn't pasted as plain text.

I recommend deleting it and downloading the zip file that GitHub provides. Then you can extract and copy the file into the right place.

![image](https://github.com/TheWeirdDev/nautilus-send-to-bluetooth/assets/6321734/111a2985-9bac-48c3-b059-5b3ce8104fac)

**Comment by curable-online** [comment]
I thought that I have installed your extension using [AUR](https://aur.archlinux.org/packages/nautilus-send-to-bluetooth). But I did it manually by copy paste.

Installed it from AUR and now it's fixed.
